### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by Furnicarium** [tetafro/shop#3]
app\views.php on line 4

ругается на синтаксическую ошибку. папки кеш и правда нет.

**Comment by tetafro** [comment]
> app\views.php on line 4

Ошибку поправил, скобка лишняя была.

> папки кеш и правда нет

Она автоматом создаётся, надо только, чтобы были права на запись в `app/templates/`.

> а чуть ниже совсем другая база данных прописана на 10 строчке

Ну там одна БД была закоменчена. Так что в итоге одна БД.

> У меня не получилось это запустить.

Тем лучше ;) Это наколеночный проект времён изучения азов PHP. Тут нет ничего полезного.
